# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Personal Website
email: gettingnumber1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This website is just a website to see how good I am at creating websites. This website was created useing Jekyll and Code
baseurl: "Personal Website" # the subpath of your site, e.g. /blog
url: "https://ethanculp.github.io" # the base hostname & protocol for your site
github_username:  EthanCulp

# Build settings
markdown: kramdown
